<?php
require 'data.php'; require 'partials.php';
$items=array_slice(products(),0,6); $dealItems=array_slice($items,0,2); $spotlight=$items[0]??null;
$weeklyMedia=$spotlight?product_media((int)($spotlight['id']??0),$spotlight['image']):[];
$weeklyVariants=$spotlight?product_variant_data((int)($spotlight['id']??0)):['sizes'=>[],'materials'=>[],'colors'=>[],'prices'=>[]];
$weeklyMaterialId=$weeklyVariants['materials'][0]['id']??0;
$weeklySizePrices=[]; foreach($weeklyVariants['sizes'] as $weeklySize)$weeklySizePrices[$weeklySize['id']]=$weeklyVariants['prices'][$weeklyMaterialId.'_'.$weeklySize['id']]??($weeklySize['price']??$spotlight['price']??0);
$weeklyInitialPrice=$weeklySizePrices[$weeklyVariants['sizes'][0]['id']??0]??($spotlight['price']??0);
$shortcuts=[['name'=>'Sofa giường mở điện','code'=>'sofa-giuong-mo-dien','filter'=>'Sofa giường mở điện','icon'=>'bi-arrow-left-right'],['name'=>'Sofa chỉnh điện','code'=>'sofa-chinh-dien','filter'=>'Sofa chỉnh điện','icon'=>'bi-sliders2-vertical'],['name'=>'Sofa modular','code'=>'sofa-modular','filter'=>'Sofa modular / góc đa năng','icon'=>'bi-grid-3x3-gap'],['name'=>'Giường nâng điện','code'=>'giuong-nang-dien','filter'=>'Giường nâng điện','icon'=>'bi-box-arrow-up'],['name'=>'Phụ kiện','code'=>'phu-kien','filter'=>'Phụ kiện','icon'=>'bi-plus-square']];
if($pdo=db())try{$rows=$pdo->query('SELECT name,code,image FROM categories ORDER BY id LIMIT 4')->fetchAll(PDO::FETCH_ASSOC);foreach($rows as $i=>$row)if(isset($shortcuts[$i]))$shortcuts[$i]=array_merge($shortcuts[$i],array_filter($row));}catch(Throwable $e){}
header_page();
?>
<main>
<section class="hero"><img src="https://ima.vn/assets/uploads/media/Famigo_000275.jpg" alt="Sofa IMA PRIME trong phòng khách"><div class="hero-content"><div class="hero-copy"><div class="eyebrow">Chuyên gia sofa thông minh, đa chức năng</div><h1>Phòng khách gọn đẹp, sofa hoá thành giường trong một chạm.</h1><p>Dựng sẵn tại xưởng Việt Nam. Chọn hôm nay, ngồi thật trong nhà bạn sau 2–3 ngày.</p><div class="hero-actions"><a class="button light" href="#bestseller">Xem sofa điện</a><a class="button outline" href="https://zalo.me/0934430111">Nhắn Zalo tư vấn ngay</a></div></div></div></section>

<section class="category-shortcuts"><div class="container"><div class="shortcut-swiper swiper"><div class="swiper-wrapper"><?php foreach($shortcuts as $s): ?><div class="swiper-slide"><a class="shortcut" href="category.php?type=<?=urlencode($s['filter'])?>"><span class="shortcut-icon"><?php if(!empty($s['image'])):?><img src="<?=htmlspecialchars(prime_asset_url($s['image']))?>" alt=""><?php else:?><i class="bi <?=htmlspecialchars($s['icon'])?>"></i><?php endif?></span><span><?=htmlspecialchars($s['name'])?></span></a></div><?php endforeach?></div></div></div></section>

<?php if($dealItems): ?><section class="container section deal-section"><div class="section-head"><div><div class="eyebrow">Ưu đãi hôm nay</div><h2>Mẫu nổi bật, sẵn sàng cho căn nhà bạn</h2></div><span class="deal-note">Số lượng có hạn tại xưởng</span></div><div class="featured-deals"><?php foreach($dealItems as $deal): ?><article class="featured-deal"><a class="featured-deal-image" href="product.php?slug=<?=urlencode($deal['slug'])?>"><img src="<?=htmlspecialchars($deal['image'])?>" alt="<?=htmlspecialchars($deal['name'])?>"></a><div class="featured-deal-copy"><span class="deal-kicker">Lựa chọn tuần này</span><h3><?=htmlspecialchars($deal['name'])?></h3><p><?=htmlspecialchars($deal['description'])?>. Hoàn thiện tại xưởng, hỗ trợ chọn màu theo không gian thực tế.</p><strong><?=money($deal['price'])?></strong><div class="hero-actions"><a class="button" href="product.php?slug=<?=urlencode($deal['slug'])?>">Xem chi tiết</a><button class="button outline-dark" type="button" data-home-add-cart data-name="<?=htmlspecialchars($deal['name'])?>" data-image="<?=htmlspecialchars($deal['image'])?>" data-price="<?=$deal['price']?>">Thêm vào giỏ</button></div></div></article><?php endforeach?></div></section><?php endif?>

<section class="benefits"><div class="container benefit-grid"><div class="benefit"><i class="bi bi-truck"></i><h3>Giao nhanh 2–3 ngày</h3><p>Bán thành phẩm dựng sẵn tại xưởng — không chờ 8–12 tuần như hàng đặt nhập khẩu.</p></div><div class="benefit"><i class="bi bi-shield-check"></i><h3>Khung 10 năm · Motor 2 năm</h3><p>Hai mốc bảo hành tách riêng. Vải bọc 1 năm với lỗi sản xuất.</p></div><div class="benefit"><i class="bi bi-house-door"></i><h3>Khung làm tại Việt Nam</h3><p>Khung và bọc vải làm tại xưởng riêng. Linh kiện điện nhập khẩu, kiểm định từng lô.</p></div><div class="benefit"><i class="bi bi-geo-alt"></i><h3>Ngồi thử tại Hà Nội</h3><p>Showroom 201 Trường Chinh, 9h–18h mỗi ngày.</p></div></div></section>

<section id="bestseller" class="container section home-bestsellers"><div class="section-head"><div><div class="eyebrow">Bán chạy tuần này</div><h2>Những mẫu khách chọn nhiều nhất</h2></div><a class="under" href="category.php">Xem toàn bộ bộ sưu tập →</a></div><div class="products"><?php foreach($items as $p): ?><a class="product-card" href="product.php?slug=<?=urlencode($p['slug'])?>"><div class="product-image product-image-switch"><img class="product-primary-image" src="<?=htmlspecialchars($p['image'])?>" alt="<?=htmlspecialchars($p['name'])?>"><?php if(!empty($p['image_secondary'])):?><img class="product-secondary-image" src="<?=htmlspecialchars($p['image_secondary'])?>" alt=""><?php endif?><span class="badge <?=$p['fast']?'':'order'?>"><?=$p['fast']?'Có sẵn giao ngay':'Đặt hàng 7–10 ngày'?></span></div><div class="product-text"><div class="product-title"><h3><?=htmlspecialchars($p['name'])?></h3><span class="rating">★ <?=$p['rating']?> · <?=$p['reviews']?></span></div><p><?=htmlspecialchars($p['description'])?></p><span class="price"><?=money($p['price'])?></span></div></a><?php endforeach?></div></section>

<section class="container spend-promo"><div><span class="eyebrow">Ưu đãi theo đơn hàng</span><h2>Chọn thêm để căn phòng trọn vẹn hơn.</h2></div><div class="spend-levels"><span><b>500.000đ</b> cho đơn từ 20 triệu</span><span><b>1.500.000đ</b> cho đơn từ 30 triệu</span></div><a class="under" href="category.php">Khám phá sản phẩm mua kèm →</a></section>

<section class="container section"><div class="video-block"><div class="video-image video-embed"><iframe src="https://www.youtube-nocookie.com/embed/vO7mYgL7XvY?rel=0" title="Video demo cơ chế sofa điện IMA PRIME" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div class="video-copy"><div class="eyebrow">Xem cơ chế hoạt động</div><h2>Một chạm để mở giường, một chạm để thu gọn.</h2><p>Video demo thật, quay tại showroom. Mỗi trang sản phẩm đều có clip riêng cho đúng mẫu bạn đang xem.</p><div class="stats"><div><strong>&lt; 8s</strong><small>mở hoàn toàn</small></div><div><strong>42 dB</strong><small>độ ồn motor</small></div><div><strong>20.000</strong><small>chu kỳ thử tải</small></div></div></div></div></section>

<section class="real-spaces section"><div class="real-space-grid"><img src="uploads/products/prime-sample/6a151bc8eb507_IMA04350.jpg" alt="Sofa Prime trong không gian thực tế"><img src="uploads/products/prime-sample/Famigo_000295.jpg" alt="Sofa Prime trong không gian thực tế"><img src="uploads/products/prime-sample/6a151bd778106_IMA04369.jpg" alt="Sofa Prime trong không gian thực tế"><img src="uploads/about/0d247336556c62a491676f84751882b8.jpg" alt="Không gian nhà khách Prime"></div></section>

<section class="reviews"><div class="container"><div class="section-head"><div><div class="eyebrow">Khách đã nhận hàng</div><h2>Chuyện giao hàng, lắp đặt và cơ cấu điện</h2></div><div><strong style="font:32px Archivo,sans-serif">4.9</strong> trên 61 đánh giá đã xác thực</div></div><div class="reviews-grid"><article class="review"><div class="stars">★★★★★</div><blockquote>“Đặt chiều thứ Năm, sáng Chủ Nhật đã có sofa trong nhà. Hai bạn giao hàng tự tháo chân, đưa qua cửa thang máy chung cư gọn gàng.”</blockquote><b>Nguyễn Thu H.</b><small>FAMIGO 2.1m · Vinhomes Smart City</small></article><article class="review"><div class="stars">★★★★★</div><blockquote>“Sáu tháng rồi, ngày nào cũng ngả 2–3 lần, motor vẫn êm. Nhà có trẻ nhỏ nên rất thích cái khoá điều khiển.”</blockquote><b>Trần Minh Đ.</b><small>CASA 2.2m · Times City</small></article><article class="review"><div class="stars">★★★★☆</div><blockquote>“Bạn tư vấn gửi video quay vải trước nên không bị bất ngờ. Ngồi chắc, phần mở giường không lún.”</blockquote><b>Lê Phương A.</b><small>NAPOLI 1.8m · Ecopark</small></article></div></div></section>

<section id="fabric" class="container section"><div class="fabric-grid"><div class="section-intro"><div class="eyebrow">Thư viện vải & màu</div><h2>Cùng một mẫu, mười hai sắc phòng khách.</h2><p>Ảnh cận cảnh từng chất liệu kèm mã màu và thành phần. Màu trên màn hình có thể chênh lệch nhẹ — liên hệ Zalo để được gửi ảnh/video thực tế.</p><br><a class="under" href="fabric-library.php">Khám phá thư viện vải →</a></div><div class="swatches" aria-label="Các màu vải"><i class="swatch"></i><i class="swatch"></i><i class="swatch"></i><i class="swatch"></i><i class="swatch"></i><i class="swatch"></i><i class="swatch"></i><i class="swatch"></i></div></div></section>

<?php if($spotlight): ?><section class="container section weekly-product"><div class="section-head"><div><div class="eyebrow">Lựa chọn nổi bật</div><h2>Sản phẩm của tuần</h2></div><a class="under" href="product.php?slug=<?=urlencode($spotlight['slug'])?>">Xem chi tiết →</a></div><?php require __DIR__.'/partials/weekly-product.php'; ?></section><?php endif?>

<section id="showroom" class="container section"><div class="showroom"><div class="showroom-text"><div class="eyebrow">Showroom</div><h2>Đến ngồi thử trước khi quyết.</h2><div class="contact-list"><div>Địa chỉ · 201 Trường Chinh, Thanh Xuân, Hà Nội</div><div>Giờ mở cửa · 9h00 – 18h00, hàng ngày</div><div>Hotline / Zalo · <a class="under" href="tel:0934430111">0934 430 111</a></div></div><div class="hero-actions"><a class="button" href="https://zalo.me/0934430111">Nhắn Zalo tư vấn</a><a class="button outline-dark" href="https://maps.google.com/?q=201+Truong+Chinh+Ha+Noi">Xem đường đi</a></div></div><div class="showroom-photo"><img src="https://ima.vn/assets/uploads/media/6a151bce2644c_IMA04360.jpg" alt="Showroom IMA PRIME"></div></div></section>
<section id="policy" class="container section"><div class="policies"><article class="policy"><h3>Bảo hành tách theo bộ phận</h3><p>Khung 10 năm · cơ cấu điện 2 năm · vải bọc 1 năm với lỗi sản xuất.</p><a class="under" href="policies.php#warranty">Xem chi tiết</a></article><article class="policy"><h3>Vận chuyển & lắp đặt</h3><p>Nội thành Hà Nội miễn phí vận chuyển và lắp đặt.</p><a class="under" href="policies.php#delivery">Xem chi tiết</a></article><article class="policy"><h3>Đổi trả trong 7 ngày</h3><p>Đổi hoặc trả sản phẩm chưa qua sử dụng.</p><a class="under" href="policies.php#returns">Xem chi tiết</a></article></div></section>
<section class="container social-cta"><i class="bi bi-camera"></i><div><div class="eyebrow">Không gian của bạn</div><h2>Chia sẻ góc nhà cùng Prime.</h2><p>Tag @imaprime trên TikTok hoặc Facebook để chúng tôi có thể đăng lại câu chuyện của bạn.</p></div><a class="under" href="https://www.facebook.com/imasofa">Theo dõi IMA PRIME →</a></section>
</main><?php footer_page(); ?>
