<?php
require '_layout.php';
$pdo=db(); $reviews=[];
if($pdo) try {$reviews=$pdo->query('SELECT r.*,p.name product_name,p.slug product_slug FROM product_reviews r JOIN products p ON p.id=r.product_id ORDER BY FIELD(r.status,"pending","approved","rejected"),r.created_at DESC')->fetchAll(PDO::FETCH_ASSOC);$images=$pdo->prepare('SELECT image_url FROM product_review_images WHERE review_id=? ORDER BY sort_order,id');foreach($reviews as &$review){$images->execute([$review['id']]);$review['images']=array_map('prime_asset_url',$images->fetchAll(PDO::FETCH_COLUMN));}unset($review);}catch(Throwable $e){}
$counts=['pending'=>0,'approved'=>0,'rejected'=>0];foreach($reviews as $review)$counts[$review['status']]++;
admin_header('Đánh giá khách hàng','reviews');admin_flash();
?>
<section class="reviews-admin"><div class="dashboard-actions"><div><div class="kicker">Customer reviews</div><h2>Đánh giá từ khách hàng</h2><p>Duyệt đánh giá trước khi hiển thị trên trang chi tiết sản phẩm.</p></div></div><div class="review-metrics"><span><b><?=$counts['pending']?></b> Chờ duyệt</span><span><b><?=$counts['approved']?></b> Đang hiển thị</span><span><b><?=$counts['rejected']?></b> Đã ẩn</span></div>
<?php if(!$pdo):?><div class="notice error">MySQL chưa kết nối.</div><?php elseif(!$reviews):?><div class="empty"><div><i class="bi bi-star"></i></div><h3>Chưa có đánh giá</h3><p>Đánh giá khách gửi từ website sẽ xuất hiện tại đây để bạn duyệt.</p></div><?php else:?><div class="review-admin-list"><?php foreach($reviews as $review):?><article class="review-admin-card"><div class="review-admin-meta"><span class="review-status <?=$review['status']?>"><?=$review['status']==='approved'?'Đang hiển thị':($review['status']==='pending'?'Chờ duyệt':'Đang ẩn')?></span><small><?=htmlspecialchars(date('d/m/Y H:i',strtotime($review['created_at'])))?></small></div><div class="review-admin-content"><div><h3><?=htmlspecialchars($review['customer_name'])?> <span><?=str_repeat('★',(int)$review['rating'])?></span></h3><a href="../product.php?slug=<?=urlencode($review['product_slug'])?>" target="_blank"><i class="bi bi-box-arrow-up-right"></i> <?=htmlspecialchars($review['product_name'])?></a><p><?=nl2br(htmlspecialchars($review['content']))?></p></div><?php if($review['images']):?><div class="review-admin-images"><?php foreach($review['images'] as $image):?><a href="<?=htmlspecialchars($image)?>" target="_blank"><img src="<?=htmlspecialchars($image)?>" alt="Ảnh review"></a><?php endforeach?></div><?php endif?></div><div class="review-admin-actions"><form method="post" action="review-action.php"><input type="hidden" name="id" value="<?=$review['id']?>"><?php if($review['status']!=='approved'):?><button class="admin-button" name="action" value="approve"><i class="bi bi-eye"></i> Hiển thị</button><?php endif?><?php if($review['status']!=='rejected'):?><button class="review-hide" name="action" value="hide"><i class="bi bi-eye-slash"></i> Ẩn</button><?php endif?><button class="review-delete" name="action" value="delete" onclick="return confirm('Xoá vĩnh viễn đánh giá này?')"><i class="bi bi-trash"></i> Xoá</button></form></div></article><?php endforeach?></div><?php endif?></section>
<?php admin_footer(); ?>
